FROM tomcat:9-alpine

ENV JAVA_OPTS="-Xmx1G -XX:PermSize=1G -XX:MaxPermSize=1G -XX:+UseCompressedOops"
EXPOSE 8080

RUN rm -rf /usr/local/tomcat/webapps/*
COPY ../target/demo-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/demo.war
CMD ["catalina.sh","run"]
